### ISSUE TITLE
Iptables line for Crowdsec-firewall-bouncer not inserted for Docker-user at reboot

### ISSUE THREAD

**Issue by Eirikr70** [crowdsecurity/cs-firewall-bouncer#141]
Hello, I use Crowdsec with a docker install. I have activated the firewall bouncer. It seems to be working well. But I meet the following issue : when restarting the host, I check Iptables and see that the Docker-user line is not inserted, although the crowdsec-firewall-bouncer.yaml includes it. I then have to restart the bouncer (sudo systemctl restart crowdsec-firewall-bouncer)  and then the line gets inserted. System is RaspberryPiOS 64-bit on a Raspberry Pi 4B, 8 Go.
**Docker-compose file**
```
---
version: "2.1"
services:
  swag:
    image: lscr.io/linuxserver/swag:latest
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Europe/Paris
      - URL=xxx.fr
      - VALIDATION=http
      - SUBDOMAINS=heim,vault,hauk,webdav,searx,file
#      - CERTPROVIDER= #optional
#      - DNSPLUGIN=cloudflare #optional
#      - PROPAGATION= #optional
#      - DUCKDNSTOKEN= #optional
      - EMAIL=eric@cespedes.fr #optional
      - ONLY_SUBDOMAINS=true #optional
#      - EXTRA_DOMAINS= #optional
      - STAGING=false #optional
    volumes:
      - ./config:/config
      - logs:/config/log
    ports:
      - 443:443
      - 80:80 #optional
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    networks:
      secure_net:
        ipv4_address: 172.120.0.2
  crowdsec:
    image: crowdsecurity/crowdsec:latest
    restart: unless-stopped
    container_name: crowdsec
    environment:
      #this is the list of collections we want to install
      #https://hub.crowdsec.net/author/crowdsecurity/collections/nginx
      COLLECTIONS: "crowdsecurity/nginx"
      GID: "${GID-1001}"
      CROWDSEC_BOUNCER_API_KEY: "xxx"
      TZ: Europe/Paris
    depends_on:
      - 'swag'
    volumes:
      - ./crowdsec/acquis.yaml:/etc/crowdsec/acquis.yaml
      - logs:/var/log
      - /var/log/auth.log:/var/log/auth.log
#      - /var/log/mail.log:/var/log/mail.log
      - crowdsec-db:/var/lib/crowdsec/data/
      - crowdsec-config:/etc/crowdsec/
    ports:
      - 8081:8080
    networks:
      secure_net:
        ipv4_address: 172.120.0.3
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
#  dashboard:
#    #we're using a custom Dockerfile so that metabase pops with pre-configured dashboards
#    image: eirikr70/metabaseforcrowdsec:arm64
#    restart: always
#    container_name: metabase
#    ports:
#      - 3000:3000
#    environment:
#      MB_DB_FILE: /data/crowdsec.db
#      MGID: "${GID-1001}"
#    depends_on:
#      - 'crowdsec'
#    volumes:
#      - crowdsec-db:/metabase-data/
#    networks:
#      secure_net:
#        ipv4_address: 172.120.0.4


volumes:
  logs:
    external: true
  crowdsec-db:
  crowdsec-config:

networks:
  secure_net:
    ipam:
      driver: default
      config:
        - subnet: 172.120.0.0/24
```

**/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml**
```
mode: iptables
pid_dir: /var/run/
update_frequency: 10s
daemonize: true
log_mode: file
log_dir: /var/log/
log_level: info
api_url: http://localhost:8081/
api_key: xxx
disable_ipv6: true
deny_action: DROP
deny_log: false
supported_decisions_types:
  - ban
#to change log prefix
#deny_log_prefix: "crowdsec: "
#to change the blacklists name
#blacklists_ipv4: crowdsec-blacklists
#blacklists_ipv6: crowdsec6-blacklists
#if present, insert rule in those chains
iptables_chains:
  - INPUT
#  - FORWARD
  - DOCKER-USER
```
**CAPI and LAPI**
```
eric@vault:~/swag $ sudo docker exec crowdsec cscli capi status
time="10-02-2022 11:32:50 PM" level=info msg="Loaded credentials from /etc/crowdsec/online_api_credentials.yaml"
time="10-02-2022 11:32:50 PM" level=info msg="Trying to authenticate with username xxx on https://api.crowdsec.net/"
time="10-02-2022 11:32:50 PM" level=info msg="You can successfully interact with Central API (CAPI)"
eric@vault:~/swag $ sudo docker exec crowdsec cscli lapi status
time="10-02-2022 11:32:58 PM" level=info msg="Loaded credentials from /etc/crowdsec/local_api_credentials.yaml"
time="10-02-2022 11:32:58 PM" level=info msg="Trying to authenticate with username localhost on http://0.0.0.0:8080/"
time="10-02-2022 11:32:58 PM" level=info msg="You can successfully interact with Local API (LAPI)"
```
