### ISSUE TITLE
nftables configuration design issues

### ISSUE THREAD

**Issue by pdf** [crowdsecurity/cs-firewall-bouncer#153]
In #111 a new configuration structure was introduced to supprt custom table/chain names, however I think this has some deficiencies, though these probably stem somewhat from the initial design.

I am investigating adding support for filter hooks other than `input` (primarily `forward`), however in attempting to do so I find that this is incompatible with the current structure, since adding support for multiple hooks requires adding multiple chains. The current structure:

```yaml
nftables:
  ipv4:
    enabled: true
    blacklist: crowdsec-blacklist
    set-only: false
    table: crowdsec
    chain: crowdsec-chain
  ipv6:
    enabled: false
    blacklist: crowdsec6-blacklist
    set-only: false
    table: crowdsec6
    chain: crowdsec6-chain
```

is clearly predicated on operating on a single chain. My initial thought was to add a `hooks` as an array of strings, however this would require `chain` to be treated as a base name (ie for `hooks: [input, filter]`, the chains might be `crowdsec6-chain-input` / `crowdsec6-chain-forward`), and I suspect this is undesirable.

For my use-case I thought I might be able to make use of the new `set-only` functionality, however this surfaces another issue: in my firewall deployments I implement blocklists on both `netdev` and `inet` address families (it's conceivable that users may also want to block on `bridge`), however the configuration structure does not allow specifying the family, nor does it allow specifying multiple tables/chains.

This leads me to believe we probably need an additional level of nesting, to allow enough flexibility to support all desired behaviour. I'd propose something like:

```yaml
nftables:
  ipv4:
    enabled: true
    targets:
    - blacklist: crowdsec-blacklist
      set-only: false
      table: crowdsec
      chain: crowdsec-chain
      family: ip # TODO: new functionality
      hook: input # TODO: new functionality
  ipv6:
    enabled: false
    targets:
    - blacklist: crowdsec6-blacklist
      set-only: false
      table: crowdsec6
      chain: crowdsec6-chain
      family: ip6  # TODO: new functionality
      hook: input # TODO: new functionality
```

Then multiple blocklists in `set-only` mode might look like:

```yaml
nftables:
  ipv4:
    enabled: true
    targets:
    - blacklist: crowdsec-blacklist-netdev
      set-only: true
      table: crowdsec-netdev
      family: netdev # TODO: new functionality
    - blacklist: crowdsec-blacklist-filter
      set-only: true
      table: crowdsec-inet
      family: inet # TODO: new functionality
```

And multiple hooks might look like:

```yaml
nftables:
  ipv4:
    enabled: true
    targets:
    - blacklist: crowdsec-blacklist
      set-only: false
      table: crowdsec
      chain: crowdsec-chain
      family: ip # TODO: new functionality
      hook: input # TODO: new functionality
    - blacklist: crowdsec-blacklist
      set-only: false
      table: crowdsec
      chain: crowdsec-chain
      family: ip # TODO: new functionality
      hook: forward # TODO: new functionality
```

This will introduce some complexity, as we'll need to dedup set operations based on `family`+`table`+`blacklist`, but this should be relatively easy to resolve. It also may require some additional config validation to avoid some obvious footguns for users.

I'd certainly be open to alternative proposals, if anyone has better ideas.

I realise there's a bit to digest here, but it would be ideal if we could examine this before the current config makes it out of pre-release to avoid breaking user configs or having to maintain backwards-compatibility (the latter would be quite ugly).
