### ISSUE TITLE
iptables firewall bouncer starting before the docker daemon on boot?

### ISSUE THREAD

**Issue by dakota-marshall** [crowdsecurity/cs-firewall-bouncer#216]
Based on my logs, it looks like by default the iptables firewall bouncer tries to initialize the iptables rules before the docker daemon can create its chain when the server is starting. Here is the error I got on boot today:

```
time="12-11-2022 06:43:29" level=info msg="iptables set-up : /usr/sbin/iptables -I DOCKER-USER -m set --match-set crowdsec-blacklists src -j DROP"
time="12-11-2022 06:43:29" level=warning msg="Error inserting set in iptables (/usr/sbin/iptables -I DOCKER-USER -m set --match-set crowdsec-blacklists src -j DROP): exit status 1 : iptables: No chain/target/match by that name.\n"
time="12-11-2022 06:43:29" level=fatal msg="iptables init failed: while inserting set in iptables: exit status 1"
```

Here is my bouncer config:

```yaml
mode: iptables
pid_dir: /var/run/
update_frequency: 10s
daemonize: true
log_mode: file
log_dir: /var/log/
log_level: info
log_compression: true
log_max_size: 100
log_max_backups: 3
log_max_age: 30
api_url: http://127.0.0.1:8080/
api_key:
insecure_skip_verify: false
disable_ipv6: true
deny_action: DROP
deny_log: false
supported_decisions_types:
  - ban
#to change log prefix
#deny_log_prefix: "crowdsec: "
#to change the blacklists name
blacklists_ipv4: crowdsec-blacklists
blacklists_ipv6: crowdsec6-blacklists
#if present, insert rule in those chains
iptables_chains:
#  - INPUT
#  - FORWARD
  - DOCKER-USER

## nftables
nftables:
  ipv4:
    enabled: true
    set-only: false
    table: crowdsec
    chain: crowdsec-chain
  ipv6:
    enabled: true
    set-only: false
    table: crowdsec6
    chain: crowdsec6-chain
# packet filter
pf:
  # an empty string disables the anchor
  anchor_name: ""
```

I haven't made any changes to either the docker systemd service or the bouncer service, but just for giggles here is what my service file looks like:

```systemd
[Unit]
Description=The firewall bouncer for CrowdSec
After=syslog.target network.target remote-fs.target nss-lookup.target crowdsec.service
Before=netfilter-persistent.service

[Service]
Type=notify
ExecStart=/usr/sbin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
ExecStartPre=/usr/sbin/crowdsec-firewall-bouncer -c /etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml -t
ExecStartPost=/bin/sleep 0.1

[Install]
WantedBy=multi-user.target

```
I have not tried adding docker.service to the After section of the unit file yet, as this is a production system. This is Ubuntu 20.04.5 if that matters either.

Any advice? Let me know if I may just be missing something
