### ISSUE TITLE
level=error msg="unable to commit delete decisions conn.Receive: netlink receive: no such file or directory"

### ISSUE THREAD

**Issue by ne20002** [crowdsecurity/cs-firewall-bouncer#230]
I just upgraded to newest version 0.0.25 and found this in the logfile
```
level=error msg="unable to commit delete decisions conn.Receive: netlink receive: no such file or directory"
```
What may be the cause of this message?

**Comment by LaurenceJJones** [comment]
Guess you use NFTABLES?

Error line:
https://github.com/crowdsecurity/cs-firewall-bouncer/blob/bb8370a6864384647b3816fe0635bc20be27a965/main.go#L222

Commit func:
https://github.com/crowdsecurity/cs-firewall-bouncer/blob/c0a9f1d4027bcc3ecbaf7b509c30bf4d98fbf454/nftables.go#L526

Searching for message returns another repo with similar issue and resolution https://github.com/google/nftables/issues/109#issuecomment-670727493

**Comment by ne20002** [comment]
As far as I see, the bouncer is creating table, chains and rules (for nftables in my case) _only_ or input hook. As I want to use it on a (OpenWrt) router I need to create my rules manually to cover forward hook.
I would like to try a new configuration with prometheus disabled but havent found info for this on documentation (https://docs.crowdsec.net/docs/bouncers/firewall/).

**Comment by alimdi** [comment]
Same problem here without any way to determine what's causing the error.
Thus the bouncer doesn't add IPs to the blacklist even if the table and chain are present.

`time="12-04-2023 13:16:48" level=debug msg="adding 162.0.209.211 to buffer "
time="12-04-2023 13:16:48" level=error msg="unable to commit add decisions conn.Receive: netlink receive: invalid argument"
time="12-04-2023 13:16:48" level=debug msg="committed added decisions"
time="12-04-2023 13:16:48" level=info msg="49614 decisions added"`

configuration :
`mode: nftables
nftables:
  ipv4:
    enabled: true
    set-only: true
    table: crowdsec
    chain: crowdsec-chain`

The set is empty

`root@ddx4:/# nft list table crowdsec
table ip crowdsec {
        set crowdsec-blacklists {
                type ipv4_addr
                flags timeout
        }

        chain crowdsec-chain {
                type filter hook input priority filter; policy accept;
                ip saddr @crowdsec-blacklists drop
        }
}`

**Comment by LaurenceJJones** [comment]
We figured out the issue is most likely linked to running nftables in ipv4 or ipv6only. We have a current RC pending if you wish to download and replace the binary with to test if it fixes for you.

**Comment by alimdi** [comment]
It's definitely working the RC version.
Thank you for your help, much appreciated.

**Comment by ne20002** [comment]
I just updated to 0.0.26-rc4 on OpenWrt. The error message still appears. :(
My bouncer config is
```
root@FB4040:/tmp/log# cat /var/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
mode: nftables
pid_dir: /var/run/
update_frequency: 10s
daemonize: true
log_mode: file
log_dir: /var/log/
log_level: info
log_compression: true
log_max_size: 100
log_max_backups: 3
log_max_age: 30
api_url: http://cs-lapi:8014/
api_key: *************************
insecure_skip_verify: true
disable_ipv6: false
deny_action: drop
deny_log: false
supported_decisions_type:
  - ban
#to change log prefix
deny_log_prefix: "crowdsec: "
#to change the blacklists name
blacklists_ipv4: crowdsec-blacklists
blacklists_ipv6: crowdsec6-blacklists
#type of ipset to use
ipset_type: nethash
#if present, insert rule in those chains
iptables_chains:
  - INPUT
#  - FORWARD
#  - DOCKER-USER
## nftables
nftables:
  ipv4:
    enabled: true
    set-only: true
    table: crowdsec
    chain: input
  ipv6:
    enabled: true
    set-only: true
    table: crowdsec6
    chain: input
# packet filter
pf:
  # an empty disables the anchor
  anchor_name: ""
prometheus:
  enabled: false
  listen_addr: 127.0.0.1
  listen_port: 60601

```
