### ISSUE TITLE
Huge Cpu on deleting/updating decissions

### ISSUE THREAD

**Issue by ne20002** [crowdsecurity/cs-firewall-bouncer#316]
I give the 0.0.27 a new try on my BPi-R3.

It seems as if updating the ipset or deleting ips from the ipset is using relativly huge amount of cpu.

```
root@BPiR3:/etc/config# cat /var/log/crowdsec-firewall-bouncer.log 
time="16-08-2023 18:05:21" level=info msg="backend type : nftables"
time="16-08-2023 18:05:21" level=info msg="nftables initiated"
time="16-08-2023 18:05:21" level=info msg="Using API key auth"
time="16-08-2023 18:05:21" level=info msg="Processing new and deleted decisions . . ."
time="16-08-2023 18:05:30" level=info msg="1250 decisions deleted"
time="16-08-2023 18:05:30" level=info msg="36551 decisions added"
time="16-08-2023 18:11:17" level=info msg="2 decisions deleted"
time="16-08-2023 18:15:22" level=info msg="2 decisions deleted"
time="16-08-2023 18:15:46" level=info msg="2 decisions deleted"
time="16-08-2023 18:20:30" level=info msg="1 decision added"
time="16-08-2023 18:26:31" level=info msg="1 decision deleted"
time="16-08-2023 18:27:29" level=info msg="2 decisions deleted"

```
And this is the rrd output:
![grafik](https://github.com/crowdsecurity/cs-firewall-bouncer/assets/39007279/c7142b28-8681-449b-8c73-0e26c3bcfa75)
![grafik](https://github.com/crowdsecurity/cs-firewall-bouncer/assets/39007279/256fbdf5-8416-4ff9-830b-fb8bc9827115)
![grafik](https://github.com/crowdsecurity/cs-firewall-bouncer/assets/39007279/72bf3b60-0669-4dba-b682-37a447bbda23)

First spikes at 20:05 (aka 18:05), second spikes at 20:10 relate to deleting just two ips from set. Increase of thermal verifies the cpu usage spikes.

System: BananaPi R3 with Openwrt 25.03-rc2 and Openwrt crowdsec-firewall-bouncer package 0.0.27.

The system is handling 20Mbit/s traffic (IPTV) with just 1% cpu for the time displayed. With starting the bouncer the increase in cpu and temperature started.

Maybe there is some room for optimizations?

Adding bigger amounts of ips (like another 16033 decissions) is creating a smaller spike.  So I wonder if there are two different ways used for adding small or bigger portions of ips.

**Comment by LaurenceJJones** [comment]
> Maybe there is some room for optimizations?

Do you have any recommendations? we already split into smaller batches only get IP based decisions. Any feedback you can provide we can explore.

**Comment by LaurenceJJones** [comment]
Maybe we should do #314 for sanity

**Comment by ne20002** [comment]
Hi
yes, I wanted the ARMv8 so I can test with my BananaPi R3. I currently have 0.0.27 running. If there is optimizations in 0.0.28 I'd be happy to test it. :)
Regarding the metrics, this is my config.yaml:

```
root@BPiR3:~# cat /var/etc/crowdsec/bouncers/crowdsec-firewall-bouncer.yaml
mode: nftables
pid_dir: /var/run/
update_frequency: 10s
daemonize: true
log_mode: file
log_dir: /var/log/
log_level: info
log_compression: true
log_max_size: 100
log_max_backups: 3
log_max_age: 30
api_url: http://cs-lapi:8014/
api_key: 399e9a936ec4918d25a47eefe3f71918
insecure_skip_verify: true
disable_ipv6: false
deny_action: drop
deny_log: false
supported_decisions_type:
  - ban
#to change log prefix
deny_log_prefix: "crowdsec: "
#to change the blacklists name
blacklists_ipv4: crowdsec-blacklists
blacklists_ipv6: crowdsec6-blacklists
#type of ipset to use
ipset_type: nethash
#if present, insert rule in those chains
iptables_chains:
  - INPUT
#  - FORWARD
#  - DOCKER-USER
## nftables
nftables:
  ipv4:
    enabled: true
    set-only: true
    table: crowdsec
    chain: input
  ipv6:
    enabled: true
    set-only: true
    table: crowdsec6
    chain: input
# packet filter
pf:
  # an empty disables the anchor
  anchor_name: ""
prometheus:
  enabled: false
  listen_addr: 127.0.0.1
  listen_port: 60601
```
