### ISSUE TITLE
[TLS Auth] Update base config.yaml to include example

### ISSUE THREAD

**Issue by LaurenceJJones** [crowdsecurity/cs-firewall-bouncer#371]
All Go based remediation support the following yaml as long as they are using our `go-cs-bouncer` library which most/all are:

```yaml
cert_path: /path/to/file
key_path: /path/to/file
ca_cert_path: /path/to/file
```
