### ISSUE TITLE
nftables : allow to customize in which tables/rules we insert

### ISSUE THREAD

**Issue by buixor** [crowdsecurity/cs-firewall-bouncer#74]
Unlike the iptables/ipset mode, the nftables mode doesn't let you configure this and only applies on input. It is missing, especially when/if you want to use those rules in forward etc.

**Comment by jarppiko** [comment]
This could get bit priority. `nftables` is becoming the standard firewall in the next Ubuntu LTS to be released in April 2022.

**Comment by jarppiko** [comment]
I decided to try to make the changes myself and I got a version up and running that _seems_ to work. I will test it first. The modified version relies on slightly different config file format: 

```
nftables:
  ipv4:
    enabled: true
    blacklist: crowdsec-blacklist
    set-only: false
    table: crowdsec
    chain: crowdsec-chain
  ipv6:
    enabled: false
    blacklist: crowdsec6-blacklist
    set-only: false
    table: crowdsec6
    chain: crowdsec6-chain
```

The idea of the `set-only` option is to allow admins to defined the place for the crowdsec blacklist in their `nftables` config and `crowdsec` only adds/removes addresses from the blacklist (set). 

I am not a `golang` programmer and this is my very first `golang` project so the code needs review. I just learned `golang` syntax just to make the fix. Shall I just send a pull request to the project?
